# Site settings
url: https://www.benmanns.com
title: Blog of Benjamin Manns
description:
email: benmanns@gmail.com
baseurl: ""
twitter_username: benmanns
github_username:  benmanns

permalink: /posts/:title

# Build settings
markdown: kramdown
