# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog of Benjamin Manns
email: benmanns@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.benmanns.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: &twitter_username benmanns
github_username: benmanns

# Build settings
markdown: kramdown
theme: minima

permalink: /posts/:title/
plugins:
  - jekyll-assets
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - octopress-minify-html

mailhide: >-
  <a href="https://www.google.com/recaptcha/mailhide/d?k=01p4aq0kLFnP8mRT5mFoT7pw==&amp;c=uEqgETHhuPHioiZ9soZvUb51S9wBZulVkUsxrkZvj-Q=" onclick="window.open('https://www.google.com/recaptcha/mailhide/d?k\07501p4aq0kLFnP8mRT5mFoT7pw\75\75\46c\75uEqgETHhuPHioiZ9soZvUb51S9wBZulVkUsxrkZvj-Q\075', '', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'); return false;" title="Reveal this e-mail address">benm...ns</a>@gmail.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _headers

# SEO Tag
twitter:
  username: *twitter_username
facebook:
 app_id: 510403205958630
 publisher: 616977745
 admins: 616977745
social:
  links:
    - https://twitter.com/benmanns
    - https://www.facebook.com/bfmanns
    - https://www.linkedin.com/in/benmanns
    - https://plus.google.com/104034123103894699115
    - https://github.com/benmanns
    - https://keybase.io/benmanns
