# Site settings
url: http://www.benmanns.com
title: Benjamin Manns
description:
email: ben@benmanns.com
baseurl: ""
twitter_username: benmanns
github_username:  benmanns

# Build settings
markdown: kramdown
